### ISSUE TITLE
What is the best url to use when validating a token?

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis-site#12]
I have asked this previously and can't find the e-mail. PC-BAGIS caches the token for a certain period of time but I want to validate it before trying to use it in a service call. I am currently just hitting the root: https://webservices.geog.pdx.edu/api/rest/ and checking for a valid response. Is there a better way to do this?

**Comment by jkeifer** [comment]
That is currently the best way to verify the token. I do believe I was
going to setup an API endpoint you could hit that would be a little bit
lighter-weight and would return a more simple response indicating only whether
the supplied token was valid or not. I will make an issue for that and will
get to it as soon as I can.

Sincerely,
Jarrett

**Comment by jkeifer** [comment]
This issue is addressed in PSU-CSAR/django-ebagis#4.
