### ISSUE TITLE
ebagis install does not increase max download size

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis-site#4]
The max download is capped by default by IIS at 30MB. This is best increased on a per-site basis, rather than by changing the system-wide setting in IIS. To do so, the following needs to be merged with the `web.config` file that gets created in the `django-ebagis_site` directory:

```
<system.webServer>
        <security>
            <requestFiltering>
                <requestLimits maxAllowedContentLength="524288000"/>
            </requestFiltering>
        </security>
</system.webServer>
```

To be specific, the `<security>` tags and their contents need to be placed between the `<system.webServer>` tags in `web.config`. For the current iteration of the test site this was done manually.

**Comment by jkeifer** [comment]
Note that like issue #6, I think this might be best fixed by adding an option to django-windows-tools to take this setting as an argument when running the command to create the site.

**Comment by jkeifer** [comment]
The commits above fixed this, though it is not great: see issue #8 .

**Comment by jdduh** [comment]
"requestLimits maxAllowedContentLength="524288000""

So this statement limits the max download size to 500MB?

**Comment by jkeifer** [comment]
I believe you are correct, that value is 500MB. However, I actually used the value 1024000000; the above was copied from an example I found. So we are limiting uploads to 1GB. If this limit is not appropriate, we can easily change it.
